import { Model, hasMany } from './model';
import { number, object, string } from './schema';

const ProductSchema = object({
  id: number().autoGenerated(),
  name: string(),
});
class ProductModel extends Model<typeof ProductSchema> {
  primaryKey = ['id', 'name'] as const;
  categories = hasMany(() => tables.categories);
}

const CategorySchema = object({
  id: number().autoGenerated(),
  name: string(),
});
class CategoryModel extends Model<typeof CategorySchema> {
  primaryKey = ['id'] as const;
  products = hasMany(() => tables.products);
}

const tables = {
  products: new ProductModel(ProductSchema),
  categories: new CategoryModel(CategorySchema),
};
