name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint affected
        run: npx nx affected -t lint
      - name: Test affected
        run: npx nx affected -t test --configuration=ci
      - name: Build affected
        run: npx nx affected -t build
